config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  resources :posts, only: [ :new, :create, :show, :edit, :update, :destroy,:index] do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  get 'reviews/new'
  resources :users, only: [:index, :show]
  resources :tops , only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post  
  belongs_to :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :food_image, FoodImageUploader
  validates :shop_name,
            :description,
            :address,
            :food_image,
            :tag_ids, presence:true
  has_many :comments
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  geocoded_by :address
  after_validation :geocode
  

  def self.search(search)
    if search
      Post.where('shop_name LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :user_image, ImageUploader
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts, dependent: :destroy
    has_many :comments
    has_many :likes, dependent: :destroy
    has_many :liked_posts, through: :likes, source: :post
    validates :user_name, presence: true,length: { maximum: 6} 
    validates :user_image, presence: true
    validates :love_brand, presence: true 
    def already_liked?(post)
      self.likes.exists?(post_id: post.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters , if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_image,:user_name,:love_brand])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_image,:user_name,:love_brand])

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end  
  end
  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
def index
    @post  = Post.all.order("created_at DESC").page(params[:page]).per(12)
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path, notice: "投稿に成功しました"
    else
      flash[:alert] = "入力内容に誤りがあります。入力漏れをご確認ください。"
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def search
    @posts = Post.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def post_params
    params.require(:post).permit(:shop_name, :description,:address, :latitude, :longitude,:food_image,:remove_food_image,tag_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @post  = Post.all.order("created_at DESC").page(params[:page]).per(12)
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
end

  def show

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order("created_at DESC").page(params[:page]).per(12)
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title gout
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:src => "//maps.google.com/maps/api/js?key=#{ENV['GOOGLE_MAP_API_KEY']}"}
    %script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}

  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/_form.html.haml
.check_box
  %span タグ
  = form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag|
    %div
      = tag.label do
        = tag.check_box
        = tag.text

app/views/posts/edit.html.haml
= render "shared/header"
.post
  .post__content
    .post__content__title
      Edit post
    .post__content__recommend
      = form_with model: @post, class: :form, local: true do |form|
        %br
        %br
        %br
        %br
        Shop name：
        = form.text_field :shop_name, placeholder: :お店の名前, class: "input-default"
        %br
        %br
        %br
        %br
        Food image：
        .foodimg
          = image_tag @post.food_image.url ,class:"foodimg", id: :food_image if @post.food_image?
        = form.file_field :food_image,id: :image__food 
        %p
          = form.check_box :remove_food_image
          Delete Image
        %br
        %br
        %br
        %br
        Description：
        = form.text_area :description, placeholder: :メニュー説明, class: "text-area"
        %br
        %br
        %br
        %br
        Adress：   
        = form.text_area :address, placeholder: :住所, class: "text-area"
        %br
        %br
        = form.submit 'Edit', class:"send__btn"

app/views/posts/index.html.haml
= render "shared/header"
= render "shared/main"
.main
  .main__title
    Narrow down
    .main__title__select-box
      = form_tag posts_path, method: :get, class: 'boards__searchForm' do
        = select_tag :tag_id ,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),{prompt: '絞り込み',onchange: 'submit(this.form);'}   
  .partition
  .main__contents
    - @posts.each do |o|
      =link_to post_path(o) do
        .tags
          - o.tags.each do |tag|
            .tag
              = tag.name
        = image_tag o.food_image.url,size:'200x200',class:"image"
        .posts__content
          .by
            by
          .icon
            .img
              = image_tag o.user.user_image.url,size:'30x30',class:"img"
            .name
              = o.user.user_name
            .likes
            %i.fas.fa-heart{:style => "color: red;"}
            = o.liked_users.count
        .partition
               
= render "shared/newpost"

app/views/posts/new.html.haml
= render "shared/header"
.post
  .post__content
    .post__content__title
      new post
    .post__content__recommend
      = form_with model: @post, class: :form, local: true do |form|
        .field
          Food image：
          #img_field{:onclick => "$('#file').click()"}
            - if @post.food_image.url.present?
              = image_tag(@user.food_image.url)
            - else
              %i.fas.fa-folder-plus.fa-8x.fa-border{:style => "color: #a7a7a7;"}
          = form.file_field :food_image, class: "image", style: "display:none;", id: "file"
        .field
          Shop name：
          = form.text_field :shop_name, placeholder: :お店の名前, class: "input-default"

        .field
          = form.label :description
          = form.text_field :description, placeholder: :メニュー説明, class: "text-area"
        .field
          = form.label :address
          = form.text_field :address, placeholder: :"住所  (例)東京都世田谷区", class: "address-area"
        .field
          = form.label :Brands
          .tags
            = form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag|
              .tagselect
                = tag.label do
                  = tag.check_box
                  = tag.text

          = form.submit 'Post !', class:"send__btn"




 
      
 
        
        

app/views/posts/search.html.haml
= render "shared/header"
.main
  .header__search
    .container
      = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "店名で検索できます", class: "search-input"
        = button_tag type: 'submit' ,class: 'search_btn' do
          = icon 'fas','search',class: 'search-icon'
  .partition
  .main__contents
    - @posts.each do |o|
      =link_to post_path(o) do
        .posts__image
          = image_tag o.food_image.url,size:'200x200',class:"image"
        .posts__content
          .post__content__name
            =o.shop_name



                  
    

app/views/posts/show.html.haml
= render "shared/header"
.post
  - if user_signed_in? && current_user.id == @post.user_id
    .delete-edition
      = link_to "Delete Post" ,post_path(@post.id), method: :delete , data: { confirm: '削除しますか？' }
    .delete-edition
      = link_to "Edit Post" ,edit_post_path(@post.id) 
  .post__content
    .post__content__topic
      .post__content__detail--contributor
        .icon
          =link_to post_path(@post.id) do
            = image_tag @post.user.user_image.url,size:'30x30',class:"img"
        .name
          = link_to user_path(@post.user) do
            = @post.user.user_name
        .shopname
          = @post.shop_name
      .title
        .like
          %h3
          - if current_user.already_liked?(@post)
            .heart.fas.fa-heart.fa-3x{:style => "color: red;"}
              = button_to  '', post_like_path(@post), method: :delete
          - else
            .heart.far.fa-heart.fa-3x{:style => "color: gray;"}
              = button_to '', post_likes_path(@post)
        .count
          = @post.liked_users.count 
      
 
          
    .post__content__recommend
    .post__content__partition
    .post__content__detail
      .tags
        - @post.tags.each do |tag|
          .tag
            = tag.name

          
        -# .brands
        -#   = @post.assortment[1..-2].gsub('",',', ').gsub("\"", "")
      .post__content__detail--post
        .content
          .img
            = image_tag @post.food_image.url,size:'300x300',class:"image"
            .time
              = icon("far", "clock")
              = @post.created_at.strftime('%Y/%m/%d %H:%M')
          .partition
          .description
            = @post.description
          .partition
          .address
            ・
            = @post.address 
            #map{:style => "width: 100%; height: 400px;"}
              :javascript
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'map'}}, function(){
                  markers = handler.addMarkers([
                    {
                      "lat": #{@post.latitude},
                      "lng": #{@post.longitude},
                      "infowindow": '<p>#{@post.shop_name}</p><p>#{@post.address}</p><p>#{link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:\#{@post.latitude},\#{@post.longitude}&iwloc=J",target: "_blank"}</p>'
                    }
                  ]);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  handler.getMap().setZoom(17);
                });
          .spase
        .reviews
          .input
            - if current_user
              = form_with(model: [@post, @comment], local: true, class: "input__contents",id: "new_comment") do |form|
                .title
                  Comment
                  .form
                    = form.text_area :content, rows: "2",class: "textbox"
                    = form.submit "SEND",class: "form__submit"
            - else
              .text
                ※ コメントの投稿には新規登録/ログインが必要です ※
            .comments
              - if @comments
                - @comments.each do |comment|
                  .data
                    .icon
                      .image
                        = image_tag comment.user.user_image.url,class:"img"
                      .name
                        = link_to comment.user.user_name, "/users/#{comment.user_id}"
                    .content
                      = comment.content
                  .partition
          
          
          

           
    

        
            
            




        

-#   .other-reviews
-#   .review-results
-#   .review-results__title
-#     .icon
-#       .img
-#       .name
-#         conributer
-#     .time
-#       07/17 07:17
-#     .input__stars
-#       .star-rating-front{:style => "width: 50%"} ★★★★★
-#       .star-rating-back ★★★★★
-#   .partition
-#   .review-results__contents
-#     まうまいんじゃないだろうか。おおおおおおおおおおおお
-# .review-results
-#   .review-results__title
-#     .icon
-#       .img
-#       .name
-#         conributer
-#     .time
-#       07/17 07:17
-#     .input__stars
-#       .star-rating-front{:style => "width: 50%"} ★★★★★
-#       .star-rating-back ★★★★★
-#   .partition
-#   .review-results__contents
-#     まずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずいまずい

app/views/shared/_header.html.haml
.header
  .header__logo
    =link_to root_path do
      Gout
  .header__logo
  .header__hum
    #ham-menu
      %ul
      - if user_signed_in?
        = image_tag current_user.user_image.url,size:'30x30',class:"img"
        .name 
          = current_user.user_name
        .partition
        .profile
          = link_to user_path(current_user.id) do
            = icon('fas','address-card')
            Profile
        .partition
        .search
          =link_to "/posts/search" do
            = icon('fas','search')
            Shop Search
        .partition
        .likes
          =link_to users_path do
            = icon('fas','users')
            All Users

        .partition
        .log_out
          = link_to destroy_user_session_path, method: :delete do
            = icon('fas','sign-out-alt')
            Log out


      - else
        .partition
        .likes
          = link_to new_user_session_path do
            = icon('fas','clipboard-check')
            Log in
        .partition
        .likes
          = link_to  new_user_registration_path do
            = icon('fas','user-edit')
            Sign up
    #menu-background

    
   

app/views/shared/_newpost.html.haml
- if user_signed_in?  
  .exhibition
    .exhibition__text
      New post
    .exhibition__icon
      = link_to  new_post_path do
        = icon('fas','beer fa-2x')
- else
  .exhibition
    .exhibition__text
      New post
    .exhibition__icon
      = link_to  new_user_session_path do
        = icon('fas','beer fa-2x')

app/views/tops/index.html.haml
= render "shared/header"
- if user_signed_in?
  = render "shared/main"
  .main
    .main__title
      All posts
      .main__title__select-box
        = form_tag posts_path, method: :get, class: 'boards__searchForm' do
          = select_tag :tag_id ,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),{prompt: '絞り込み',onchange: 'submit(this.form);'}   
    .partition
    .main__contents
      - @post.each do |o|
        =link_to post_path(o) do
          .tags
            - o.tags.each do |tag|
              .tag
                = tag.name
            -# = o.assortment[1..-2].gsub('",',', ').gsub("\"", "")
          = image_tag o.food_image.url,size:'200x200',class:"image"
          .posts__content
            .by
              by
            .icon
              .img
                = image_tag o.user.user_image.url,size:'30x30',class:"img"
              .name
                = o.user.user_name
              .likes
              %i.fas.fa-heart{:style => "color: red;"}
              = o.liked_users.count
          .partition 
  = paginate(@post)
  = render "shared/newpost"
  
- else
  .toppage
    .toppage__content
      .toppage__content--title
        Gout
      .toppage__content--description
        あなたが大好きなビールが置いてあるお店を一瞬で見つけられます。
        お店のビールの情報と一緒に自分のお気に入りメニューを投稿することもできます。
      .buttons
        .link
          - if user_signed_in?
            = link_to posts_path do
              始める
          - else
            = link_to new_user_session_path do
              始める
        .link
          = link_to top_path(:id) do
            使い方
          
      

app/views/tops/show.html.haml
= render "shared/header"
.wrapper
  .descr
    = icon('fas','question-circle')
    Goutとは
    .descr-contents
      ビール好きのための居酒屋投稿アプリです。
    .descr-contents
      %span{:style => "color: darkorange"}
        = icon('fas','bahai')
        お店ごとのビールの銘柄を確認できます。
  .down
    = icon('fas','angle-double-down fa-3x')
  .descr
    ・飲み屋のビール銘柄とおすすめメニューを投稿するアプリです
    %br/
    %br/
    .img
      = image_tag("紹介1.jpg")
  .descr
    ・投稿はビールの銘柄で絞り込めます
    %br/
    %br/
    .img
      = image_tag("紹介5.png")
  .descr
    ・お店の名前から検索もできます
    %br/
    %br/
    .img
      = image_tag("説明8.png")
  .descr
    ・右上のハンバーガメニューから、好きなページに飛べます。
    %br/
    %br/
    .img2
      = image_tag("説明.png")
  .descr
    ・投稿に対して他のユーザーがコメント、いいねを行えます。
    %br/
    %br/
    .img
      = image_tag("説明7.png")
  .descr
    ・自分がした投稿といいねした投稿をプロフィールで確認できます。
    %br/
    %br/
    .img
      = image_tag("説明9.jpg")
    %br/
    %br/
  .descr
    是非ご利用くださいませ!!
  .down
    = icon('fas','angle-double-down fa-3x')
  .start
    = link_to new_user_session_path do
      始める





  

app/views/users/index.html.haml
= render "shared/header"
= render "shared/main"
.main
  .main__title
    All users
  .partition
  .main__contents
    - @users.each do |user|
      = link_to user_path(user) do
        = image_tag user.user_image.url,size:'200x200',class:"image"
        .user__content
          .name
            = user.user_name
          .contents
            = icon('fas','pen')
            = user.posts.count
            = icon('fas','beer')
            = user.love_brand
  = paginate(@users)

app/views/users/show.html.haml
= render "shared/header"
.personal
  .personal__profile
    .contents
      = image_tag @user.user_image.url,size:'180x180',class:"main_image"
      .main_name
        = @user.user_name
      - if user_signed_in? && current_user.id.to_s == params[:id]
        - unless @user.email == "test@gmail.com"
          .edition
            = link_to "Edit Profile " ,edit_user_registration_path 
  .tabs
    %input#all{:checked => "checked", :name => "tab_item", :type => "radio"}/
    %label.tab_item{:for => "all"} My Posts
    %input#programming{:name => "tab_item", :type => "radio"}/
    %label.tab_item{:for => "programming"} Likes
    #all_content.tab_content
      .tab_content_description
        - @posts.each do |o|
          =link_to post_path(o) do
            = image_tag o.food_image.url,size:'200x200',class:"image"
            .posts__content
              = icon('fas','heart')
              = o.liked_users.count
              = icon('fas','clock')
              = o.created_at.strftime('%Y/%m/%d %H:%M')


        .personal__title__select-box
    #programming_content.tab_content
      .tab_content_description
        - @user.liked_posts.each do |post|
          =link_to "#" do
            = image_tag post.food_image.url,size:'200x200',class:"image"
            .icon
              .img
                = image_tag post.user.user_image.url,size:'20x20',class:"img"
              .name
                = post.shop_name
              




    
  



  